bb-usb-gadgets (1.20260421.1)
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/bb-usb-gadgets/suite/trixie/debian/bb-start-acm-ncm-rndis-old-gadget b/bb-usb-gadgets/suite/trixie/debian/bb-start-acm-ncm-rndis-old-gadget
--- a/bb-usb-gadgets/suite/trixie/debian/bb-start-acm-ncm-rndis-old-gadget
+++ b/bb-usb-gadgets/suite/trixie/debian/bb-start-acm-ncm-rndis-old-gadget
@@ -1,27 +1,13 @@
 #!/bin/sh -e
+
+# SPDX-FileCopyrightText: 2013 Robert Nelson <robertcnelson@gmail.com>
 #
-# Copyright (c) 2013-2021 Robert Nelson <robertcnelson@gmail.com>
-#
-# Permission is hereby granted, free of charge, to any person obtaining a copy
-# of this software and associated documentation files (the "Software"), to deal
-# in the Software without restriction, including without limitation the rights
-# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-# copies of the Software, and to permit persons to whom the Software is
-# furnished to do so, subject to the following conditions:
-#
-# The above copyright notice and this permission notice shall be included in
-# all copies or substantial portions of the Software.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
-# THE SOFTWARE.
+# SPDX-License-Identifier: MIT
 
 #Based off:
 #https://github.com/beagleboard/meta-beagleboard/blob/master/meta-beagleboard-extras/recipes-support/usb-gadget/gadget-init/g-ether-load.sh
+
+#Sync with: https://github.com/armbian/build/blob/main/packages/bsp/usb-gadget-network/setup-usbgadget-network.sh
 
 if [ -f /etc/default/bb-mac-addr ] ; then
 	. /etc/default/bb-mac-addr
@@ -41,22 +27,11 @@ fi
 
 log="usb_gadget:"
 
-usb_gadget="/sys/kernel/config/usb_gadget"
+CONFIGFS="/sys/kernel/config/usb_gadget"
 
-#  idVendor           0x1d6b Linux Foundation
-#  idProduct          0x0104 Multifunction Composite Gadget
-#  bcdDevice            4.04
-#  bcdUSB               2.00
-
-usb_idVendor="0x1d6b"
-usb_idProduct="0x0104"
-usb_bcdDevice="0x0404"
-usb_bcdUSB="0x0200"
 usb_serialnr="000000"
 usb_product="USB Device"
 
-usb_iserialnumber="1234BBBK5678"
-#usb_iserialnumber="$(cat /proc/device-tree/serial-number)"
 usb_imanufacturer="BeagleBoard.org"
 usb_iproduct="$(cat /proc/device-tree/model | sed "s/ /_/g" | tr -d '\000')"
 
@@ -80,16 +55,31 @@ if [ -f /etc/default/usb-oem ] ; then
 	. /etc/default/usb-oem
 fi
 
-run_libcomposite () {
-	if [ ! -d /sys/kernel/config/usb_gadget/g_multi/ ] ; then
-		echo "${log} Creating g_multi"
-		mkdir -p /sys/kernel/config/usb_gadget/g_multi || true
-		cd /sys/kernel/config/usb_gadget/g_multi
+#  idVendor           0x1d6b Linux Foundation
+#  idProduct          0x0104 Multifunction Composite Gadget
+#  bcdDevice            4.04
+#  bcdUSB               2.00
 
-		echo ${usb_bcdUSB} > bcdUSB
-		echo ${usb_idVendor} > idVendor # Linux Foundation
-		echo ${usb_idProduct} > idProduct # Multifunction Composite Gadget
-		echo ${usb_bcdDevice} > bcdDevice
+# Default values for USB-related deviceinfo variables
+usb_idVendor="${deviceinfo_usb_idVendor:-0x1D6B}"   # Linux Foundation
+usb_idProduct="${deviceinfo_usb_idProduct:-0x0104}" # Multifunction Composite Gadget
+usb_bcdDevice="${deviceinfo_usb_bcdDevice:-0x0404}"
+usb_bcdUSB="${deviceinfo_usb_bcdUSB:-0x0200}"
+
+usb_serialnumber="${deviceinfo_usb_serialnumber:-1234BBBK5678}"
+
+run_libcomposite () {
+	if [ ! -d ${CONFIGFS}/g_multi/ ] ; then
+		echo "${log} Setting up g_multit through configfs"
+		# Create an usb gadet configuration
+		mkdir -p ${CONFIGFS}/g_multi || echo "  Couldn't create $CONFIGFS/g_multi"
+
+		echo ${usb_idVendor} > "$CONFIGFS/g_multi/idVendor"
+		echo ${usb_idProduct} > "$CONFIGFS/g_multi/idProduct"
+		echo ${usb_bcdDevice} > "$CONFIGFS/g_multi/bcdDevice"
+		echo ${usb_bcdUSB} > "$CONFIGFS/g_multi/bcdUSB"
+
+		cd ${CONFIGFS}/g_multi
 
 		# Windows extension to use IAD (Interface Association Descriptor)
 		# https://learn.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-interface-association-descriptor
@@ -165,7 +155,7 @@ run_libcomposite () {
 		#fi
 	fi
 
-	cd /sys/kernel/config/usb_gadget/g_multi
+	cd ${CONFIGFS}/g_multi
 
 	ls /sys/class/udc/ > UDC
 
@@ -176,7 +166,7 @@ run_libcomposite () {
 
 use_libcomposite () {
 	echo "${log} Looking for libcomposite"
-	if [ -d /sys/kernel/config/usb_gadget/ ] ; then
+	if [ -d ${CONFIGFS}/ ] ; then
 		run_libcomposite
 	fi
 }
